### PR TITLE
Revert "Revert "Acoustics Module API""

### PR DESCRIPTION
**Pull request by ssolson**
Reverts MHKiT-Software/MHKiT#78

This is a little silly but this will revert my mistaken revert

### CODE REVIEW

**Comment by ssolson** [comment]
@akeeste sincere apologies for acting too hastily. Can you review this?

**Comment by akeeste** [comment]
Not a problem, looks good to me.

**Comment by ssolson** [comment]
For the documentation I would say no. The rebase issues arise from trying to keep 2 branches with the same commit history e.g. develop/ master.

**Comment by akeeste** [comment]
@ssolson Sounds good. merging now

**Pull request merged**
