### PR TITLE
Fix warnings in documentation build

### PR DESCRIPTION
**Pull request by akeeste**
This PR attempts to fix the plethora of warnings that appear in our current documentation build. Not all of them are critical but the vast number of warnings makes it very difficult to see if a PR is building successfully or introducing warnings.

I will note the various problems and solutions. Hopefully this can help future users building sphinx documentation here or elsewhere:

- [x] pygments lexer name 'ipython3' is not known
   - Fix: ``pip install ipython`` in the build steps
- [x] python and matlab references missing
   - Fix: remove references, these sections were removed previously
- [x] X document is not included in the toctree
   - Fix: using nbgallery to showcase examples in icons and add them to the toctree at the same time
- [x] depreciation of current method for google analytics
   - Fix: use sphinxcontrib-googleanalytics
- [x] pandoc error with examples
   - Fix: ``conda install pandoc`` in the build steps
- [x] duplicate explicit target name
   - Fix: this could be an internal reference that is duplicated, but is typically an external URL that creates a named reference. Make targets for links anonymous: `` `Title <link>`__`` (that's TWO underscores for an anonymous reference)
- [x] WARNING: image file not readable: PATH/FILENAME.png [image.not_readable]
   - Fix: resolved in source, see separate comment below
- [x] <unknown> :XX: SyntaxWarning: invalid escape sequence '\s'
   - Fix: coming from some of the graphics modules, [e.g.](https://github.com/MHKiT-Software/MHKiT-Python/actions/runs/11847231300/job/33016498618?pr=354#step:6:80). Fixed in MHKiT-Software/MHKiT-Python#360
- [ ] docstring indentation issues in source code
   - Fix: hopefully future linting catches these. There are many and the exact problems end up very ambiguous.
- [ ] docstring of mhkit.river.performance.power_coefficient:1: WARNING: duplicate object description of mhkit.river.performance.power_coefficient, other instance in MHKiT\docs\source\mhkit-matlab\api.river.rst, use :noindex: for one of them [docutils]
   - Fix: This warning will likely occur for DOLfYN as well. Currently I'm leaning towards turn this particular warning off
- [x] API formatting issues
   - Fix: I will standardize the formatting for the API documentation across modules and create a template for new modules
- [x] inline emphasis start-string without end-string
   - Fix: occurs in the swan example due to the text "*.mat files". Single escape chars (\) work in markdown for the notebook but still throw a sphinx warning. Double escape chars (\\) result in one showing up in the markdown of the notebook but removes the sphinx warning. There should be an easy solution to typing an asterisk but apparently is not. Super annoying. Perhaps to do with nbsphinx converting notebooks. Making that line code for now as that seems to work 
- [ ] html_static_path entry '_static' is placed inside outdir 
   - Fix: TBD, probably a path in the conf.py. This will be addressed in future work to automatically build/deploy the docs

### CODE REVIEW

**Comment by akeeste** [comment]
I'd like to fix the warning on duplicate object descriptions, and then merge this PR. This will cover many but not all warnings.

**Comment by akeeste** [comment]
The Python ``api.*.rst`` files have the largest changes, but content is primarily restructured and not fundamentally changed. Changes there include:
- removing redundant information - replacing manually written headers with module level docstrings where available
- proper placement of the autosummary table (concise summary table of functions in a module) - below the module level docstring and above the detail function descriptions
- standardized formatting across all modules

The MATLAB ``api.*.rst`` files were not updated because autosummary is not available for MATLAB and there are no module level docstrings available in MATLAB

**Comment by akeeste** [comment]
@simmsa @ssolson This is ready for review. See note [here](https://github.com/MHKiT-Software/MHKiT/pull/80#issuecomment-2515425792) for explanation of the changes in the api.*.rst files as those typically have the most lines changes.

@simmsa I updated the MATLAB API docs based on v0.5.0. Should we add summary tables for DOLfYN functions too?

**Review by ssolson — COMMENTED** [review]
@akeeste from a fresh install of the MHKiT repository I was able to build the docs. 

I get 1 warning when I build the repository `WARNING: html_static_path entry '_static' is placed inside outdir`

```
$ ./make.bat html
..\MHKiT-Python\examples\acoustics_example.ipynb
..\MHKiT-Python\examples\ADCP_Delft3D_TRTS_example.ipynb
..\MHKiT-Python\examples\adcp_example.ipynb
..\MHKiT-Python\examples\adv_example.ipynb
..\MHKiT-Python\examples\cdip_example.ipynb
..\MHKiT-Python\examples\Delft3D_example.ipynb
..\MHKiT-Python\examples\directional_waves.ipynb
..\MHKiT-Python\examples\environmental_contours_example.ipynb
..\MHKiT-Python\examples\extreme_response_contour_example.ipynb
..\MHKiT-Python\examples\extreme_response_full_sea_state_example.ipynb
..\MHKiT-Python\examples\extreme_response_MLER_example.ipynb
..\MHKiT-Python\examples\loads_example.ipynb
..\MHKiT-Python\examples\metocean_example.ipynb
..\MHKiT-Python\examples\mooring_example.ipynb
..\MHKiT-Python\examples\PacWave_resource_characterization_example.ipynb
..\MHKiT-Python\examples\power_example.ipynb
..\MHKiT-Python\examples\qc_example.ipynb
..\MHKiT-Python\examples\river_example.ipynb
..\MHKiT-Python\examples\short_term_extremes_example.ipynb
..\MHKiT-Python\examples\strain_measurement_example.ipynb
..\MHKiT-Python\examples\SWAN_example.ipynb
..\MHKiT-Python\examples\tidal_example.ipynb
..\MHKiT-Python\examples\tidal_performance_example.ipynb
..\MHKiT-Python\examples\upcrossing_example.ipynb
..\MHKiT-Python\examples\wave_example.ipynb
..\MHKiT-Python\examples\wecsim_example.ipynb
..\MHKiT-Python\examples\WPTO_hindcast_example.ipynb
       27 file(s) copied.
Running Sphinx v8.1.3
loading translations [en]... done
WARNING: html_static_path entry '_static' is placed inside outdir
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
checking bibtex cache... out of date
parsing bibtex file C:\Users\sterl\Codes\MHKiT\docs\source\MHKiT-Python.bib... parsed 1 entries
parsing bibtex file C:\Users\sterl\Codes\MHKiT\docs\source\MHKiT-MATLAB.bib... parsed 1 entries
[autosummary] generating autosummary for: ADCP_Delft3D_TRTS_example.ipynb, Delft3D_example.ipynb, PacWave_resource_characterization_example.ipynb, SWAN_example.ipynb, WPTO_hindcast_example.ipynb, acoustics.rst, acoustics_example.ipynb, adcp_example.ipynb, adv_example.ipynb, api.rst, ..., tidal.rst, tidal_example.ipynb, tidal_performance_example.ipynb, troubleshooting.rst, upcrossing_example.ipynb, utils.rst, wave.rst, wave_example.ipynb, webinars.rst, wecsim_example.ipynb
Writing evaluated template result to C:\Users\sterl\Codes\MHKiT\docs\_static\nbsphinx-code-cells.css
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 69 source files that are out of date
updating environment: [new config] 69 added, 0 changed, 0 removed
reading sources... [100%] wecsim_example
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... 
copying static files... 
Writing evaluated template result to C:\Users\sterl\Codes\MHKiT\docs\_static\basic.css
Writing evaluated template result to C:\Users\sterl\Codes\MHKiT\docs\_static\documentation_options.js
Writing evaluated template result to C:\Users\sterl\Codes\MHKiT\docs\_static\language_data.js
Writing evaluated template result to C:\Users\sterl\Codes\MHKiT\docs\_static\js\versions.js
copying static files: done
copying extra files... 
copying extra files: done
copying assets: done
writing output... [100%] wecsim_example
generating indices... genindex mat-modindex py-modindex done
copying linked files... 
copying notebooks ... [100%] wecsim_example.ipynb
highlighting module code... [100%] pecos.utils
writing additional pages... search done
copying images... [100%] ../doctrees/nbsphinx/wecsim_example_31_0.png
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 1 warning.

The HTML pages are in ..

..\MHKiT-MATLAB\examples\adcp_example.html
..\MHKiT-MATLAB\examples\adv_example.html
..\MHKiT-MATLAB\examples\cdip_example.html
..\MHKiT-MATLAB\examples\delft3d_example.html
..\MHKiT-MATLAB\examples\environmental_contours_example.html
..\MHKiT-MATLAB\examples\extreme_response_contour_example.html
..\MHKiT-MATLAB\examples\extreme_response_full_sea_state_example.html
..\MHKiT-MATLAB\examples\loads_example.html
..\MHKiT-MATLAB\examples\power_example.html
..\MHKiT-MATLAB\examples\qc_example.html
..\MHKiT-MATLAB\examples\river_example.html
..\MHKiT-MATLAB\examples\short_term_extremes_example.html
..\MHKiT-MATLAB\examples\SWAN_example.html
..\MHKiT-MATLAB\examples\tidal_example.html
..\MHKiT-MATLAB\examples\wave_example.html
..\MHKiT-MATLAB\examples\wecsim_example.html
..\MHKiT-MATLAB\examples\WPTO_hindcast_example.html
       17 file(s) copied.
Build finished. The HTML pages are in ..
```

**Review by ssolson — APPROVED** [review]

**Comment by akeeste** [comment]
Thanks @ssolson. I still get that warning too. It will likely be addressed when automating the documentation build, which will be a future PR.

**Comment by akeeste** [comment]
Merging this so that I can rebuild the docs.

**Pull request merged**
