### PR TITLE
Matlab updates

### PR DESCRIPTION
**Pull request by rpauly18**
PR for Matlab reseals changes.

### CODE REVIEW

**Comment by rpauly18** [comment]
@kmruehl I think this is ready to merge, but it would not hurt to have another set of eyes look it over if you have a chance.

**Comment by kmruehl** [comment]
@rpauly18 I finally have some time to review this PR. So far it looks good, but can you give a brief recap of what should be changed? I'm assuming it's primarily the MHKiT-MATLAB API and examples, is that correct?

**Comment by rpauly18** [comment]
Hi Kelley, That is correct. I also updated the required MATLAB version if using Python 3.8 in the installation section.

**Comment by kmruehl** [comment]
@mfaltas-sandia this PR may resolve some of your questions, @rpauly18 has already added a note about the MATLAB/Python versions.

**Review by kmruehl — APPROVED** [review]
@rpauly18 I've review this, resolve a few minor issues and will merge it now.

**Comment by kmruehl** [comment]
@rpauly18 you can delete your branch now if you want

**Pull request merged**
