### PR TITLE
Docs V0.3.1

### PR DESCRIPTION
**Pull request by ssolson**
- Update release notes
 - Add MATLAB WEC-SIm example

### CODE REVIEW

**Comment by ssolson** [comment]
image
The version up here must come from the init file

**Comment by ssolson** [comment]
Hey Rebecca could you remind me if I needed to update anything in the docs beyond the release notes? I added the WECsim Matlab example but other than that left the docs the same.

**Comment by kmruehl** [comment]
> 
> 
> image
> The version up here must come from the init file

@ssolson yep, it's configured in the `conf.py` file to tag the version from the init file.

**Review by rpauly18 — APPROVED** [review]
Looks good. Thanks for taking care of this, Sterling!

**Pull request merged**
