### PR TITLE
Add Separate MHKiT-MATLAB installation instructions

### PR DESCRIPTION
**Pull request by simmsa**
This separates out installation instructions for MHKiT-MATLAB and rewrites the installation to include:

* Recommended software
* Explicit instructions for each step
* Screenshots
* Advanced installation

Additional changes include:

* Addition of examples overview page
* Addition of api and example links on module overview pages

### CODE REVIEW

**Comment by simmsa** [comment]
This is addressing #55 and updating other sections of the documentation including:

1. Adding a new page specifically for MHKiT-MATLAB installation
  * Add screenshots for each section
  * Add advanced section that uses miniconda 

2. Updating Python installation instructions
  * Add recommend section for installing with Anaconda?
  * Update the minimum python version to 3.8
  * Add a recommended python version of 3.10?
    * IMO this seems to be the version that has the least build errors

3. Adding a section about troubleshooting netcdf/hdf5 errors
  * Verify your conda environment
  * Verify your pip packages
  * Verify your mhkit version 
  * Verify your python version
 
4. Removing any old or outdated information:
  * Do we still need the python 2.7 macos note?
  * Do we need the Requirements section? Is this relevant to installation if this is transparent to the user using `pip install`. This should probably be somewhere, I'm just not sure if the installation page is the right place.

**Comment by simmsa** [comment]
@rpauly18 and @akeeste,

This PR is good to go:

At a high level this adds:

* Separate MHKiT-MATLAB installation instructions
* A new MHKiT-Examples page with examples separated into broad marine energy categories
* Links to examples and api documentation on each module overview page.

**Review by rpauly18 — COMMENTED** [review]
On the MHKIT-Matlab instruction page: 
1) please add a step for actually downloading or cloning MHKIT-Matlab. In step 4 you refer to navigating to the MHKIT-Matlab folder, but there is never instruction to actually downloading that

2) Small nitpicky comment - in step 2.4 Python 3.9 is recommended, but the image shows creating the environment in 3.10. I recommend making the image match the recommendation 

3) the way the instruction in step 5.2 is worded is a bit confusing. Maybe change to "In the MATLAB command window type the command below, replacing the <python executable location> with the python executable location from above:"

4) in step 7, why is it stating that the output from circular is a Python tuple? At this point it should be returning a Matlab data type

**Comment by simmsa** [comment]
@rpauly18, thank you for the review! The latest commits incorporate changes that fix all of your recommended changes.





> 1. please add a step for actually downloading or cloning MHKIT-Matlab. In step 4 you refer to navigating to the MHKIT-Matlab folder, but there is never instruction to actually downloading that

I added step 4 detailing instructions for downloading the MHKiT-MATLAB repository

> 2. Small nitpicky comment - in step 2.4 Python 3.9 is recommended, but the image shows creating the environment in 3.10. I recommend making the image match the recommendation

Changed to 3.10. I was thinking that 3.9 was a good option, but 3.10 is what I chose initially and that should work for most users

> 3. the way the instruction in step 5.2 is worded is a bit confusing. Maybe change to "In the MATLAB command window type the command below, replacing the  with the python executable location from above:"

Updated 6.2 (previously 5.2) instructions to clarify executable location

> 4. in step 7, why is it stating that the output from circular is a Python tuple? At this point it should be returning a Matlab data type

Updated step 8 (previously 7) MATLAB circular output figure to use the MHKiT-MATLAB command.

**Review by rpauly18 — APPROVED** [review]
Thanks for making the requested changes! This looks great.

**Pull request merged**
